GET company-detail endpoint added
companieshouse/company-profile-api pull request #128
Opened 2024-02-29 11:16 UTC by YaaseenR

2024-03-01 10:47 UTC, YaaseenR commented
Added company-detail endpoint in controller class 
Added getCompanyDetails method in service class. Gets data using companyNumber and creates and returns company-detail object
Unit and integration tests all pass

2024-03-01 14:14 UTC, JAndrewCH requested changes

2024-03-01 14:14 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java
> +            "Company Profile GET request returns a 404 Resource Not found response when no company profile found")
We should change the name to say 'Company Detail GET'

2024-03-01 14:14 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java
> +    @Test()
Same here

2024-03-04 09:48 UTC, maddytjCH approved these changes

2024-03-04 10:32 UTC, SALMANCH007 approved these changes

2024-03-06 09:54 UTC, JAndrewCH approved these changes

2024-03-06 10:16 UTC, JAndrewCH submitted a review, later dismissed

2024-03-06 10:59 UTC, SALMANCH007 approved these changes

2024-03-06 11:00 UTC, merged