Feature/dsnd 1893
companieshouse/company-profile-api pull request #136
Opened 2024-03-08 15:24 UTC by maddytjCH

- Create method to determine the status of Overdue for Confirmation Statement, Next Accounts, and Annual Return.
- Added unit tests to test true & false outcomes.
- itests seemingly unaltered by this, possibly needs looking into.

2024-03-11 07:55 UTC, JAndrewCH requested changes

2024-03-11 07:55 UTC, JAndrewCH commented on src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
> +        try {
Lots of potential null pointer exceptions here

2024-03-11 07:55 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
> +    }
lets have a test with some null objects as well

2024-03-11 14:06 UTC, JAndrewCH approved these changes

2024-03-11 14:16 UTC, JAndrewCH approved these changes

2024-03-12 10:41 UTC, lbedrosyanCH approved these changes

2024-03-12 10:50 UTC, JAndrewCH approved these changes

2024-03-12 10:59 UTC, merged