DSND-627: Removed transactional configuration
companieshouse/company-profile-api pull request #58
Opened 2022-05-25 17:28 UTC by vchitti-kainos

2022-05-26 09:13 UTC, iichr commented on src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
> +                    companyNumber)));
I believe this needs to be thrown as a `BadRequestException` as it was originally (mainly due to the status code expected)

2022-05-26 09:21 UTC, iichr requested changes
Just a few bits that need addressed to preserve existing behaviour

2022-05-26 09:21 UTC, iichr commented on src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
> -                + "contextId %s and company number %s", contextId, companyNumber));
This log is specifically added as part of a logging requirement - please keep and move immediately after the successful `invokeChsKafkaApi` call.

2022-05-26 09:21 UTC, iichr commented on src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
> +                throw new RuntimeException(errorMessage);
All of this and more already happens in `src/main/java/uk/gov/companieshouse/company/profile/api/InsolvencyApiService.java` in the `invokeChsKafkaApi` method, no need to log and throw the same exception again.

2022-05-26 09:29 UTC, amobarak approved these changes

2022-05-27 09:07 UTC, iichr approved these changes

2022-05-27 10:33 UTC, merged